feeder/Models/HistoFeedModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace feeder.Models
{
    public class HistoFeedModel
    {
        public string Day { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
    }
}

feeder/Models/TodaysDate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace feeder.Models
{
    public class TodaysDate
    {
        public int TDay { get; set; }
        public string TMonth { get; set; }
        public int TMonthInt { get; set; }
        public int TYear { get; set; }
    }
}

feeder/Models/testModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace feeder.Models
{
    public class TestModel
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Subject { get; set; }
    }
}

feeder/Controllers/HistoFeedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using feeder.Models;
using System.Web.Script.Serialization;
using System.Net;

namespace feeder.Controllers
{
    public class HistoFeedController : Controller
    {
        // GET: HistoFeed

        public ActionResult Index()
        {
            var Today = new TodaysDate
            {
                TDay = DateTime.Now.Day,
                TMonth = DateTime.Now.ToString("MMMM"),
                TYear = DateTime.Now.Year

            };
            return View(Today);
        }

        [HttpPost]
        public ActionResult GetHistoFeeds(string Day, string Month, string Year) {

            var url = "https://clientapi.gcs-web.com/data/73872e17-9913-4f7d-8204-45fa1b438d57/quotes/lookup/weekof?date=" + Year + "-" + Month + "-" + Day + "&symbol=OMCL";

            var client = new WebClient();
            var content = client.DownloadString(url);
            var serialize = new JavaScriptSerializer();
            var jsonContent = serialize.Deserialize<Object>(content);

            return Json(jsonContent, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetHistoFeedThisWeek()
        {
            var ThisDay = DateTime.Now.Day.ToString().PadLeft(2,'0');
            var ThisMonth = DateTime.Now.Month.ToString().PadLeft(2, '0');
            var ThisYear = DateTime.Now.Year.ToString();

            var url = "https://clientapi.gcs-web.com/data/73872e17-9913-4f7d-8204-45fa1b438d57/quotes/lookup/weekof?date=" + ThisYear + "-" + ThisMonth + "-" + ThisDay + "&symbol=OMCL";

            var client = new WebClient();
            var content = client.DownloadString(url);
            var serialize = new JavaScriptSerializer();
            var jsonContent = serialize.Deserialize<Object>(content);

            return Json(jsonContent, JsonRequestBehavior.AllowGet);
        }
    }
}

feeder/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace feeder.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

feeder/Controllers/SecFillingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Web.Script.Serialization;

namespace feeder.Controllers
{
    public class SecFillingController : Controller
    {
        // GET: SecFilling
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetSecFilings()
        {

            var url = "https://clientapi.gcs-web.com/data/73872e17-9913-4f7d-8204-45fa1b438d57/filings";

            var client = new WebClient();
            var content = client.DownloadString(url);
            var serialize = new JavaScriptSerializer();
            var jsonContent = serialize.Deserialize<Object>(content);

            return Json(jsonContent, JsonRequestBehavior.AllowGet);
        }
    }
}

feeder/Views/HistoFeed/GetHistoFeed.cshtml
@model feeder.Models.HistoFeedModel
@{
    ViewBag.Title = "GetHistoFeed";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GetHistoFeed</h2>
<br />
<br />

feeder/Views/HistoFeed/GetHistoFeedThisWeek.cshtml
@{
    ViewBag.Title = "GetHistoFeedThisWeek";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>GetHistoFeedThisWeek</h2>
@Url

feeder/Views/HistoFeed/HistoFeed.cshtml
@model feeder.Models.TodaysDate

@{
    ViewBag.Title = "HistoFeed";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Historic Stock Lookup</h2>
<br /><br />
<select id="Month" name="Month" onchange="GetHistoData()">
    @for (var i = 1; i <= 12; i++)
    {
        var dt = new DateTime(2000, i, 1).ToString("MMMM");
        if (DateTime.Now.Month == i)
        {
            <option value="@i.ToString().PadLeft(2,'0')" selected>Lookup Month: @dt</option>
        }
        else
        {
            <option value="@i.ToString().PadLeft(2,'0')">Lookup Month: @dt</option>
        }

    }
</select>
<select id="Day" name="Day" onchange="GetHistoData()">
    @for (var i = 1; i <= 31; i++)
    {
        if (DateTime.Now.Day == i)
        {
            <option value="@i.ToString().PadLeft(2,'0')" selected>Lookup Day: @i</option>
        }
        else
        {
            <option value="@i.ToString().PadLeft(2,'0')">Lookup Day: @i</option>
        }

    }
</select>
<select id="Year" name="Year" onchange="GetHistoData()">
    @for (int i = 2000; i <= DateTime.Now.Year; i++)
    {
        if (DateTime.Now.Year == i)
        {
            <option value="@i" selected>Lookup Year: @i</option>
        }
        else
        {
            <option value="@i">Lookup Year: @i</option>
        }

    }
</select>

<hr />
<br /><br />
      <div class="btn-group">
          <button type="button" class="btn btn-danger">Action</button>
          <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <span class="sr-only">Toggle Dropdown</span>
          </button>
          <div class="dropdown-menu">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">Separated link</a>
          </div>
      </div>
<hr />
<br /><br />
<div class="stitle"><h3 class="defaultToday">Week of @Model.TMonth @Model.TDay, @Model.TYear</h3></div>
<hr />
<br /><br />
<table width="100%" border="1" cellpadding="5" cellspacing="5">
    <thead>
        <tr>
            <th>DATE REQUESTED</th>
            <th>CLOSING TIME</th>
            <th>VOLUME</th>
            <th>SPLIT ADJUSTMENT FACTOR</th>
            <th>OPEN PRICE</th>
            <th>DAY HIGH</th>
            <th>DAY LOW</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

feeder/Views/HistoFeed/Index.cshtml
@model feeder.Models.TodaysDate

@{
    ViewBag.Title = "HistoFeed";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Historic Stock Lookup</h2>
<br /><br />
<select id="Month" name="Month" onchange="GetHistoData()">
    @for (var i = 1; i <= 12; i++)
    {
        var dt = new DateTime(2000, i, 1).ToString("MMMM");
        if (DateTime.Now.Month == i)
        {
            <option value="@i.ToString().PadLeft(2,'0')" selected>Lookup Month: @dt</option>
        }
        else
        {
            <option value="@i.ToString().PadLeft(2,'0')">Lookup Month: @dt</option>
        }

    }
</select>
<select id="Day" name="Day" onchange="GetHistoData()">
    @for (var i = 1; i <= 31; i++)
    {
        if (DateTime.Now.Day == i)
        {
            <option value="@i.ToString().PadLeft(2,'0')" selected>Lookup Day: @i</option>
        }
        else
        {
            <option value="@i.ToString().PadLeft(2,'0')">Lookup Day: @i</option>
        }

    }
</select>
<select id="Year" name="Year" onchange="GetHistoData()">
    @for (int i = 2000; i <= DateTime.Now.Year; i++)
    {
        if (DateTime.Now.Year == i)
        {
            <option value="@i" selected>Lookup Year: @i</option>
        }
        else
        {
            <option value="@i">Lookup Year: @i</option>
        }

    }
</select>

<hr />
<br /><br />
<div class="btn-group">
    <button type="button" class="btn btn-danger">Action</button>
    <button type="button" class="btn btn-danger dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="sr-only">Toggle Dropdown</span>
    </button>
    <div class="dropdown-menu">
        <a class="dropdown-item" href="#">Action</a>
        <a class="dropdown-item" href="#">Another action</a>
        <a class="dropdown-item" href="#">Something else here</a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#">Separated link</a>
    </div>
</div>
<hr />
<br /><br />
<div class="stitle"><h3 class="defaultToday">Week of @Model.TMonth @Model.TDay, @Model.TYear</h3></div>
<hr />
<br /><br />
<h4 class="loading">LOADING...</h4>
<table id="histoLookup" width="100%" border="1" cellpadding="5" cellspacing="5">
    <thead>
        <tr>
            <th>DATE REQUESTED</th>
            <th>CLOSING TIME</th>
            <th>VOLUME</th>
            <th>SPLIT ADJUSTMENT FACTOR</th>
            <th>OPEN PRICE</th>
            <th>DAY HIGH</th>
            <th>DAY LOW</th>
        </tr>
    </thead>
    <tbody></tbody>
</table>

feeder/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

feeder/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

feeder/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

feeder/Views/SecFilling/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>SEC Filing</h2>
<h4 class="loading">LOADING...</h4>
<table id="secFiling" width="100%" cellpadding="5" cellspacing="5" border="1">
<thead>
    <tr>
        <th>Filing Date</th>
        <th>Form</th>
        <th>Description</th>
        <th>View</th>
    </tr>
</thead>
    <tbody>
    </tbody>
</table>

feeder/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script>
        
        $(function () {
            // Loader
            $(document).ajaxStart(function () { $('.loading').show(); });
            $(document).ajaxComplete(function () { $('.loading').hide(); });

            //Get Histo Lookup Feed
            $.get('@Url.Action("GetHistoFeedThisWeek", "HistoFeed")', function (response) {
                $.each(response.data, function () {
                    $('#histoLookup tbody').append('<tr><td>'
                        + this.tradeDate + '</td><td>'
                        + this.close + '</td><td>'
                        + this.volume + '</td><td>'
                        + this.splitAdjustmentFactor + '</td><td>'
                        + this.open + '</td><td>'
                        + this.high + '</td><td>'
                        + this.low + '</td></tr>');
                });
            }); 

            //Get SEC Filing Feed
            $.get('@Url.Action("GetSecFilings", "SecFilling")', function (response) {
                $.each(response.data, function () {
                    $('#secFiling tbody').append('<tr><td>'
                        + this.dateFiled.date + '</td><td>'
                        + this.formType + '</td><td>'
                        + this.description + '</td><td>'
                        + '<a href="' + this.formats.html.url + '" target="_blank">HTML</a> | <a href="' + this.formats.pdf.url +'" target="_blank">PDF</a></td></tr>');
                });
            }); 
        });

        function GetHistoData() {
            var day = $('#Day').val();
            var month = $('#Month').val();
            var year = $('#Year').val();
            var monthText = $('#Month option:selected').text();

            $.ajax({
                type: 'post',
                url: '@Url.Action("GetHistoFeeds", "HistoFeed")',
                data: JSON.stringify({ Day: day, Month: month, Year: year }),
                contentType: 'application/json; charset=utf-8',
                dataType: 'json',
                success: function (result) {
                    $('tbody tr, h3').remove();
                    $('.stitle').append('<h3>Week of ' + monthText.replace('Lookup Month: ','') + ' ' + day + ', ' + year + '</h3>');
                    $.each(result.data, function () {
                        $('#histoLookup tbody').append('<tr><td>' + this.tradeDate + '</td><td>' + this.close + '</td><td>' + this.volume + '</td><td>' + this.splitAdjustmentFactor + '</td><td>' + this.open + '</td><td>' + this.high + '</td><td>' + this.low + '</td></tr>');
                    });
                },
                error: function (result) {
                    console.log(result);
                }
            });
        }

        $('#addastudent').on('click', function () {
            $('.loading').show();
            var firstName = $('#FirstName').val();
            var lastName = $('#LastName').val();
            var subject = $('#Subject').val();
            var data = { 'FirstName': firstName, 'LastName': lastName, 'Subject': subject };
            

            $.ajax({
                type: 'post',
                url: '@Url.Action("AddStudent", "Test")',
                data: data,
                dataType: 'html',
                success: function (result) {
                    $('input[type=text]').val("");
                    $('.loading').hide();
                    $('.ewan').append('| ' + this.FirstName + ' | ' + this.LastName + ' | ' + this.Subject + ' |<br>');
                    console.log(result);
                },
                error: function (result) {
                    console.log(result);
                }
            });
        });
    </script>
</body>
</html>